<script type="text/javascript">
	var rand = 0;

	function ready() {
	  let pubBtn = document.getElementById('publishBtn');
	  if (pubBtn) {
	    pubBtn.onclick = evt => {
	      startAgoraBroadcast();
	    };
	  }

	  getMedia()
	    .then(str => {
	      stream     = str;
	      let vidWin = document.getElementsByTagName('video')[0];
	      if (vidWin) {
	        $('#basic-stream').removeClass('hidden');
	        vidWin.srcObject = stream;
	      }
	    })
	    .catch(e => {
	      $('#remote-media').html('<div class="valign empty_state"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M3.27,2L2,3.27L4.73,6H4A1,1 0 0,0 3,7V17A1,1 0 0,0 4,18H16C16.2,18 16.39,17.92 16.54,17.82L19.73,21L21,19.73M21,6.5L17,10.5V7A1,1 0 0,0 16,6H9.82L21,17.18V6.5Z" fill="currentColor"></path></svg> getUserMedia Error: '+e+'</div>');
	    });
	}

var agoraAppId = '<?php echo($wo['config']['agora_app_id']) ?>';
var channelName = "<?php echo($wo['AgorachannelName']) ?>";

var client = AgoraRTC.createClient({mode: 'live', codec: 'vp8'});
var mainStreamId;

var localAudioTrack = null;
var localVideoTrack = null;

var localStreams = {
  uid: rand,
  camera: {
    camId: '',
    micId: '',
  }
};

var devices = {
  cameras: [],
  mics: []
};

async function getCameraDevices() {
  console.log("Checking for Camera Devices.....");
  var cameras = await AgoraRTC.getCameras();
  devices.cameras = cameras;
  cameras.forEach(function(camera, i) {
    var name = camera.label;
    var optionId = 'camera_' + i;
    var deviceId = camera.deviceId;
    if (i === 0 && localStreams.camera.camId === '') {
      localStreams.camera.camId = deviceId;
    }
    $('#camera-list').append('<a class="dropdown-item pointer" id="' + optionId + '">' + name + '</a>');
  });
  $('#camera-list a').click(function(event) {
    var index = event.target.id.split('_')[1];
    changeStreamSource(index, "video");
  });
}

async function getMicDevices() {
  console.log("Checking for Mic Devices.....");
  var mics = await AgoraRTC.getMicrophones();
  devices.mics = mics;
  mics.forEach(function(mic, i) {
    var name = mic.label;
    var optionId = 'mic_' + i;
    var deviceId = mic.deviceId;
    if (i === 0 && localStreams.camera.micId === '') {
      localStreams.camera.micId = deviceId;
    }
    if (name.split('Default - ')[1] != undefined) {
      name = '[Default Device]';
    }
    $('#mic-list').append('<a class="dropdown-item pointer" id="' + optionId + '">' + name + '</a>');
  });
  $('#mic-list a').click(function(event) {
    var index = event.target.id.split('_')[1];
    changeStreamSource(index, "audio");
  });
}

async function changeStreamSource(deviceIndex, deviceType) {
  console.log('Switching stream sources for: ' + deviceType);
  var deviceId;
  if (deviceType === "video") {
    deviceId = devices.cameras[deviceIndex].deviceId;
    if (localVideoTrack) {
      await localVideoTrack.setDevice(deviceId);
      localStreams.camera.camId = deviceId;
    }
  }
  if (deviceType === "audio") {
    deviceId = devices.mics[deviceIndex].deviceId;
    if (localAudioTrack) {
      await localAudioTrack.setDevice(deviceId);
      localStreams.camera.micId = deviceId;
    }
  }
}

async function startAgoraBroadcast() {
  try {
    client.setClientRole('host');
    var token = generateToken();
    var uid = await client.join(agoraAppId, channelName, token, 0);
    localStreams.uid = uid;
    console.log('User ' + uid + ' joined channel successfully');

    localAudioTrack = await AgoraRTC.createMicrophoneAudioTrack();
    localVideoTrack = await AgoraRTC.createCameraVideoTrack({
      encoderConfig: '720p_2'
    });

    $('#main_live_video').html('');
    localVideoTrack.play('main_live_video');
    await client.publish([localAudioTrack, localVideoTrack]);
    console.log('Local tracks published');

    getCameraDevices();
    getMicDevices();

    $('#publishBtn').removeAttr('disabled');
    $('#publishBtn').text("<?php echo($wo['lang']['please_wait']); ?>");
    $('#publishBtn').addClass('hidden');
    $('.wow_end_live_btn').removeClass('hidden');

    $.post(Wo_Ajax_Requests_File() + "?f=live&s=create", {stream_name: channelName, token: token}, function(data, textStatus, xhr) {
      if (data.status == 200) {
        $('#live_post_id').val(data.post_id);
        $('.live_mic_cam_switch').removeClass('hidden');
        setTimeout(function () {
          image = capture_video_frame("video" + uid, 'png');
          var thumb = new File([base64_2_blob(image.dataUri)], "thumb.png", {type: "image/png"});
          var formData = new FormData();
          formData.append('thumb', thumb);
          formData.append('post_id', data.post_id);
          if (node_socket_flow == "1") {
            socket.emit("user_followers_notification", { user_id: _getCookie("user_id")});
          }
          $.ajax({
            processData: false,
            url: Wo_Ajax_Requests_File() + "?f=live&s=create_thumb",
            type: 'POST',
            dataType: 'json',
            data: formData,
            contentType: false,
          });
        }, 500);
      }
    });
  } catch (err) {
    console.log('[ERROR] : startAgoraBroadcast failed', err);
  }
}

client.on('user-published', async function(user, mediaType) {
  await client.subscribe(user, mediaType);
  if (mediaType === 'video') {
    user.videoTrack.play('main_live_video');
  }
  if (mediaType === 'audio') {
    user.audioTrack.play();
  }
});

client.on('user-left', function(user) {
  console.log('Remote user has left the channel: ' + user.uid);
});

function generateToken() {
  return "<?php echo($wo['AgoraToken']); ?>";
}
</script>
