<tr class="setting-userlist <?php echo ($wo['report']['seen'] == 0) ? ' report-not-seen' : '';?> " id="ReportID_<?php echo $wo['report']['id']?>" data_selected="<?php echo($wo['report']['id']) ?>" style="vertical-align:middle;">
   <td><input type="checkbox" id="check-data-<?php echo($wo['report']['id']) ?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo($wo['report']['id']) ?>"></label></td>
   <td><?php echo $wo['report']['id']?></td>
   <td class="pointer">
      <?php if (!empty($wo['report']['reason']) && in_array($wo['report']['reason'], $wo['config']['report_reasons'])) {
         echo $wo['lang'][$wo['report']['reason']];
      }else{
         echo ucfirst($wo['report']['type']);
      } ?>
   </td>
   <td>
      <a href="<?php echo $wo['report']['reporter']['url']; ?>" style="display:flex;align-items:center;gap:8px;">
      <img src="<?php echo $wo['report']['reporter']['avatar'];?>" class="setting-avatar" style="width:36px;height:36px;object-fit:cover;border-radius:50%;flex-shrink:0;" alt="Reporter avatar">
      <span><?php echo $wo['report']['reporter']['name']; ?></span>
      </a>
   </td>
   <td>
      <?php if ($wo['report']['type'] == 'post'): ?>
         <a href="<?php echo $wo['report']['story']['url']; ?>">
           <?php echo $wo['lang']['open_post'];?>
         </a>
      <?php elseif($wo['report']['type'] == 'profile'): ?>
         <a href="<?php echo $wo['report']['user']['url']; ?>">
            <?php echo $wo['report']['user']['name']; ?>
         </a>
      <?php elseif($wo['report']['type'] == 'page'): ?>
         <a href="<?php echo $wo['report']['page']['url']; ?>">
            <?php echo $wo['report']['page']['page_name']; ?>
         </a>
      <?php elseif($wo['report']['type'] == 'group'): ?>
         <a href="<?php echo $wo['report']['group']['url']; ?>">
            <?php echo $wo['report']['group']['group_name']; ?>
         </a>
      <?php elseif($wo['report']['type'] == 'comment'): ?>
         <a href="<?php echo $wo['report']['comment']['fullurl']; ?>" target="_blank">
          <?php echo $wo['report']['comment']['Orginaltext'];?>
         </a>
      <?php endif; ?>
   </td>
   <td>
      <div class=" ajax-time" title="<?php echo date('c',$wo['report']['time']); ?>">
         <?php echo Wo_Time_Elapsed_String($wo['report']['time']);?>
      </div>
   </td>
   <td style="min-width:260px;">
      <div style="display:flex;flex-wrap:wrap;gap:4px;">
      <button class="btn bg-success admn_table_btn" onclick="Wo_MarkSafeReportedPost(<?php echo $wo['report']['id']?>,'hide');">Delete Report</button>
      <button class="btn bg-danger admn_table_btn" onclick="Wo_DeleteReportedContent(<?php echo intval($wo['report']['user']['id'])?>,<?php echo $wo['report']['id']?>,'user','hide');">Delete User</button>
      <button class="btn bg-info admn_table_btn" onclick="$('#read_report').modal().find('.report_text').text('<?php echo htmlspecialchars($wo['report']['text']); ?>')">View Report</button>
      <?php if (!empty($wo['report']['user']['id']) && $wo['report']['user']['id'] != $wo['user']['user_id']) { ?>
      <?php if ($wo['report']['user']['banned'] == 1) { ?>
         <button class="btn bg-secondary admn_table_btn" onclick="Wo_UnBanUser(<?php echo $wo['report']['user']['id'] ?>,'hide');">Unban User</button>
      <?php }else{ ?>
      <button class="btn bg-secondary admn_table_btn" onclick="Wo_BanUser(<?php echo $wo['report']['user']['id'] ?>,'hide');">Ban User</button>
      <?php } ?>
      <?php } ?>
      </div>
   </td>
</tr>