<?php
// SECURITY: Block sensitive config values from being exposed via API
// The entire list was previously commented out, exposing ALL config (SMTP passwords, S3 keys, Twilio creds, etc.)
$non_allowed_config = array(
    'reCaptchaKey', 'reCaptchaSecretKey',
    'smtp_username', 'smtp_host', 'smtp_password', 'smtp_port', 'smtp_encryption', 'smtp_or_mail',
    'sms_username', 'sms_password', 'sms_phone_number', 'sms_t_phone_number',
    'sms_twilio_username', 'sms_twilio_password',
    'amazone_s3_s_key', 'amazone_s3_key', 'amazone_s3', 'amazone_s3_bucket_name', 'region',
    'facebookAppId', 'facebookAppKey',
    'googleAppId', 'googleAppKey', 'google_map_api',
    'twitterAppId', 'twitterAppKey',
    'linkedinAppId', 'linkedinAppKey',
    'VkontakteAppId', 'VkontakteAppKey',
    'instagramAppId', 'instagramAppkey',
    'video_accountSid', 'video_apiKeySid', 'video_apiKeySecret', 'video_configurationProfileSid',
    'stripe_secret', 'stripe_id', 'paystack_secret_key', 'paystack_public_key',
    'coinpayments_merchant_id', 'coinpayments_ipn_secret', 'coinpayments_public_key', 'coinpayments_private_key',
    'eapi', 'server_key', 'purchase_code',
    'siteEmail', 'censored_words', 'mime_types',
    'OkAppId', 'OkAppPublickey', 'OkAppSecretkey',
    'tiktok_client_key', 'tiktok_client_secret',
    'authy_token', 'patreon_client_id', 'patreon_client_secret',
    'cashfree_client_id', 'cashfree_client_secret',
    'razorpay_key_id', 'razorpay_key_secret',
    'securionpay_key', 'securionpay_public_key',
    'aamarpay_store_id', 'aamarpay_signature_key',
    'fortumo_service_id', 'fortumo_api_key',
    'ngenius_api_key', 'ngenius_outlet_id',
    'last_backup', 'is_ok'
);
// $non_allowed_config = array(
//     'reCaptchaKey',
//     'googleAnalytics',
//     'AllLogin',
//     'googleLogin',
//     'facebookLogin',
//     'twitterLogin',
//     'linkedinLogin',
//     'VkontakteLogin',
//     'facebookAppId',
//     'facebookAppKey',
//     'googleAppId',
//     'googleAppKey',
//     'twitterAppId',
//     'twitterAppKey',
//     'linkedinAppId',
//     'linkedinAppKey',
//     'VkontakteAppId',
//     'VkontakteAppKey',
//     'smtp_username',
//     'smtp_host',
//     'smtp_password',
//     'smtp_port',
//     'smtp_encryption',
//     'sms_or_email',
//     'sms_username',
//     'sms_password',
//     'sms_phone_number',
//     'eapi',
//     'post_limit',
//     'user_limit',
//     'css_upload',
//     'smooth_loading',
//     'video_chat',
//     'video_accountSid',
//     'video_apiKeySid',
//     'video_apiKeySecret',
//     'video_configurationProfileSid',
//     'monthly_boosts',
//     'yearly_boosts',
//     'lifetime_boosts',
//     'instagramAppId',
//     'instagramAppkey',
//     'instagramLogin',
//     'smtp_or_mail',
//     'maintenance_mode',
//     'developers_page',
//     'order_posts_by',
//     'groups',
//     'pages',
//     'games',
//     'last_backup',
//     'is_ok',
//     'profile_privacy',
//     'emailValidation',
//     'emailNotification',
//     'seoLink',
//     'reCaptcha',
//     'profileVisit',
//     'censored_words',
//     'online_sidebar',
//     'second_post_button',
//     'useSeoFrindly',
//     'cacheSystem',
//     'sms_t_phone_number',
//     'amazone_s3_s_key',
//     'amazone_s3_key',
//     'sms_twilio_username',
//     'sms_twilio_password',
//     'amazone_s3',
//     'siteEmail',
//     'mime_types',
//     'logo_url',
//     'classified_currency_s',
//     'classified_currency',
//     'amount_ref',
//     'amount_percent_ref',
//     'google_map_api'
// );

$non_allowed = array(
    'password',
    'background_image_status',
    'email_code',
    'type',
    'start_up',
    'start_up_info',
    'startup_follow',
    'startup_image',
    'id',
    'cover_full',
    'cover_org',
    'avatar_org',
    'app_session',
    'last_email_sent',
    'sms_code',
    'pro_time',
    'css_file',
    'src',
    'followers_data',
    'following_data',
    'likes_data',
    'album_data',
    'groups_data',
    'sidebar_data',
    'showlastseen',
    'joined',
    'social_login',
    // SECURITY: Block sensitive fields from being exposed to other users
    'ip_address',
    'two_factor', 'two_factor_verified', 'two_factor_method', 'two_factor_hash',
    'google_secret', 'authy_id',
    'time_code_sent',
    'new_email', 'new_phone',
    'referrer', 'ref_user_id',
    'last_login_data',
    'android_m_device_id', 'ios_m_device_id', 'android_n_device_id', 'ios_n_device_id',
    'backup_codes',
    'lat', 'lng', // Prevent exact geolocation exposure to other users
);